name: Jekyll Site CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the site in the jekyll/builder container
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future && ls -l . && cp -rf ./ _site && ls -l _site"
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1.0.8
        

  deploy:
    if: ${{ github.ref == 'refs/heads/docs' }}
    needs: build
    concurrency:
      group: 'github-pages'
      cancel-in-progress: true
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
